"""Add downloads count for gamebuild

Revision ID: 119327604744
Revises: 151f0616d679
Create Date: 2013-01-09 15:05:37.838536

"""

# revision identifiers, used by Alembic.
revision = '119327604744'
down_revision = '151f0616d679'

from alembic import op
import database as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GameBuild', sa.Column('downloads', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GameBuild', 'downloads')
    ### end Alembic commands ###
