"""Replace unique index with plain index

Revision ID: 141348f489f
Revises: 119327604744
Create Date: 2013-01-09 16:42:02.815979

"""

# revision identifiers, used by Alembic.
revision = '141348f489f'
down_revision = '119327604744'

from alembic import op
import database as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("name", "GameBuild")
    op.create_index("name", "GameBuild", ["name"])
    op.drop_index("name", "Game")
    op.create_index("name", "Game", ["name"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("name", "GameBuild")
    op.create_unique_constraint("name", "GameBuild", ["name"])
    op.drop_index("name", "Game")
    op.create_unique_constraint("name", "Game", ["name"])
    ### end Alembic commands ###
