"""init

Revision ID: 151f0616d679
Revises: None
Create Date: 2013-01-08 11:02:36.484464

"""

# revision identifiers, used by Alembic.
revision = '151f0616d679'
down_revision = None

from alembic import op
import database as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
