"""Download History table

Revision ID: 4532dd7d856e
Revises: 173de5bbe259
Create Date: 2013-02-19 10:58:40.909293

"""

# revision identifiers, used by Alembic.
revision = '4532dd7d856e'
down_revision = '173de5bbe259'

from alembic import op
import database as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DownloadHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_cnt', sa.Integer(), nullable=False),
    sa.Column('peer_cnt', sa.Integer(), nullable=False),
    sa.Column('ipv4', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['GameBuild.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_DownloadHistory_ipv4', 'DownloadHistory', ['ipv4'])
    op.create_index('ix_DownloadHistory_country_code', 'DownloadHistory', ['country_code'])
    op.create_index('ix_DownloadHistory_downloaded_at', 'DownloadHistory', ['downloaded_at'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DownloadHistory')
    ### end Alembic commands ###
